services:
  - type: web
    name: syllabus-rag-qna
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port 10000
    plan: free
